# -*- coding: utf-8 -*-
"""PlantDiseaseDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpqP2T0E0rePodBEOLuiHwj_U5JhXqaI

**DAY ONE **
"""

import torch
import numpy as np
import matplotlib.pyplot as plt

t1=torch.tensor([1.0,2.0,3.0])
t2=torch.tensor([[1,2,3],[3,4,5]])
t3=torch.zeros(3,4)
t4=torch.rand(2,3)

print("1D tensor :", t1)
print("2D tensor :", t2.shape)
print("3D tendor :", t3)
print("Random tensor :", t4)

print("PyTorch Version:", torch.__version__)
print("GPU available:",torch.cuda.is_available())

"""Basic Operations like Numpy"""

a= torch.tensor([1.0,2.0,3.0])
b= torch.tensor([4.0,5.0,6.0])
print("Add:", a+b)
print("Mulitpy:", a*b)
print("Dot product:", torch.dot(a,b))

"""plot a sine wave"""

x = np.linspace(0,2*np.pi,100)
y = np.sin(x)

plt.plot(x,y, color='teal',linewidth=2)
plt.title("Sin Wave - My First DL Plot!")
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.grid(True)
plt.show()

"""**DAY TWO**

single perceptron from scratch
"""

import numpy as np
import matplotlib.pyplot as plt

class Perceptron:
  def __init__(self, learning_rate=0.1, epochs=100):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.weights = None
    self.bias = 0

  def step_function(self, x):
    return 1 if x >=0 else 0

  def predict(self, x):
    linear_output = np.dot(self.weights, x) + self.bias
    return self.step_function(linear_output)

  def train(self, X, y):
    self.weights = np.zeros(X.shape[1])
    for epoch in range(self.epochs):
      for xi, yi in zip(X, y):
        prediction = self.predict(xi)
        error = yi - prediction

        self.weights += self.learning_rate * error * xi
        self.bias += self.learning_rate * error

  def step_function(self, x):
    return 1 if x >=0 else 0

  def predict(self, x):
    linear_output = np.dot(self.weights, x) + self.bias
    return self.step_function(linear_output)

  def train(self, X, y):
    self.weights = np.zeros(X.shape[1])

    for epoch in range(self.epochs):
      for xi, yi in zip(X, y):
        prediction = self.predict(xi)
        error = yi - prediction

        self.weights += self.learning_rate * error * xi
        self.bias += self.learning_rate * error

X_and = np.array([[0,0],[0,1],[1,0],[1,1]])
y_and = np.array([0,0,0,1])

p = Perceptron(learning_rate=0.1, epochs=100)
p.train(X_and, y_and)

print("AND gate result:")
for xi, yi in zip(X_and,y_and):
  pred = p.predict(xi)
  print(f" Input {xi} -> predicted: {pred}, actual: {yi}")

y_or = np.array([0,1,1,1])
p2=Perceptron()
p2.train(X_and, y_or)

print("OR gate result:")
for xi, yi in zip(X_and,y_or):
  pred = p2.predict(xi)
  print(f" Input {xi} -> predicted: {pred}, actual: {yi}")

y_xor = np.array([0,1,1,0])
p3=Perceptron(epochs=1000)
p3.train(X_and, y_xor)

print("XOR gate result:")
for xi, yi in zip(X_and,y_xor):
  pred = p3.predict(xi)
  status = "OK" if pred == yi else "WRONG"
  print(f" Input {xi} -> predicted: {pred}, actual: {yi}  [{status}]")

"""notes"""

import torch
torch.__version__

"""**DAY THREE**"""

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np

x = torch.linspace(-5, 5, 100)
fig, axes = plt.subplots(1, 3, figsize=(12, 4))
axes[0].plot(x.numpy(), torch.relu(x).numpy(), color='teal')
axes[0].set_title("ReLU: max(0, x)")
axes[1].plot(x.numpy(), torch.sigmoid(x).numpy(), color='blue')
axes[1].set_title("Sigmoid: 1/(1+exp^-x)")
axes[2].plot(x.numpy(), torch.tanh(x).numpy(), color='purple')
axes[2].set_title("Tanh")
for ax in axes:
  ax.grid(True);ax.axhline(0, color='black', lw=0.5)
plt.tight_layout()
plt.show()

#build MLP using nn.sequential
model_simple= nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)
print("Simple model:", model_simple)

#Cell 3: Build same model using nn.Module (proper way)
class MyMLP(nn.Module):
   def __init__(self):
      super().__init__()
      self.layer1 = nn.Linear(2, 4)
      self.layer2 = nn.Linear(4, 1)
   def forward(self, x):
      x = torch.relu(self.layer1(x))
      x = torch.sigmoid(self.layer2(x))
      return x
model = MyMLP()
print("Custom model:", model)


# Cell 4: Solve XOR with this network!
X_xor = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
y_xor = torch.tensor([[0],[1],[1],[0]], dtype=torch.float32)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
criterion = nn.BCELoss()
for epoch in range(5000):
   output = model(X_xor)
   loss = criterion(output, y_xor)
   optimizer.zero_grad()
   loss.backward()
   optimizer.step()

print("XOR Predictions after training:")
with torch.no_grad():
   preds = model(X_xor)
   for i, (x, y) in enumerate(zip(X_xor, y_xor)):
       print(f" {x.tolist()} -> {preds[i].item():.3f} (actual: {y.item()})")

"""**DAY FOUR**"""

import torch
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.backward()
print(f"y = {y.item()}, dy/dx at x=3 = {x.grad.item()}")

w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
lr = 0.01

X_data = torch.tensor([1.0, 2.0, 3.0, 4.0])
y_data = torch.tensor([3.0, 5.0, 7.0, 9.0])

for step in range(100):
  pred = w * X_data + b # Forward pass
  loss = ((pred - y_data) ** 2).mean() # MSE Loss
  loss.backward() # Backward pass (compute gradients)

  with torch.no_grad(): # Update weights (no grad tracking here)
    w -= lr * w.grad
    b -= lr * b.grad
    w.grad.zero_() # Reset gradients to zero!
    b.grad.zero_()
  if step % 20 == 0:
    print(f"Step {step}: loss={loss.item():.4f}, w={w.item():.3f}, b={b.item():.3f}")
print(f"Final: y = {w.item():.2f}x + {b.item():.2f} (target: y = 2x + 1)")

import torch.nn as nn
import matplotlib.pyplot as plt
model = nn.Linear(1, 1) # One input, one output
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
X = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y = torch.tensor([[3.0],[5.0],[7.0],[9.0]])

losses = []
for epoch in range(200):
  pred = model(X) # 1. Forward pass
  loss = criterion(pred, y) # 2. Compute loss
  optimizer.zero_grad() # 3. Zero gradients
  loss.backward() # 4. Backprop
  optimizer.step() # 5. Update weights
  losses.append(loss.item())

plt.plot(losses, color='teal')
plt.title("Loss Curve — Learning Happening Here!")
plt.xlabel("Epoch"); plt.ylabel("MSE Loss"); plt.grid(True)
plt.show()

"""**DAY FIVE**"""

import torch
from torch.utils.data import Dataset, DataLoader
class XORDataset(Dataset):
    def __init__(self):
        self.X = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
        self.y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float32)
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx] # Returns one sample at a time

dataset = XORDataset()
loader = DataLoader(dataset, batch_size=2, shuffle=True)

print("Total samples:", len(dataset))
print("Batch size: 2")

# Cell 2: Train with DataLoader
import torch.nn as nn
model = nn.Sequential(nn.Linear(2,4), nn.ReLU(), nn.Linear(4,1), nn.Sigmoid())
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = nn.BCELoss()
for epoch in range(1000):
      for batch_X, batch_y in loader: # DataLoader gives us batches!
          pred = model(batch_X)
          loss = criterion(pred, batch_y)
          optimizer.zero_grad()
          loss.backward()
          optimizer.step()
          if epoch % 200 == 0:
              with torch.no_grad():
                full_pred = model(dataset.X)
                full_loss = criterion(full_pred, dataset.y)
                print(f"Epoch {epoch}: Loss = {full_loss.item():.4f}")

# Cell 3: Save and Load model
torch.save(model.state_dict(), 'xor_model.pth')
print("Model saved!")

# Load it back
loaded_model = nn.Sequential(nn.Linear(2,4), nn.ReLU(), nn.Linear(4,1), nn.Sigmoid())
loaded_model.load_state_dict(torch.load('xor_model.pth'))
loaded_model.eval()
print("Model loaded!")

# Verify predictions
with torch.no_grad():
    test = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
    preds = (loaded_model(test) > 0.5).float()
    print("XOR predictions:", preds.flatten().tolist())

"""**SIX DAY**"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import convolve

image = np.array([
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,255,255,255,255,0,0],
    [0,0,255,255,255,255,0,0],
    [0,0,255,255,255,255,0,0],
    [0,0,255,255,255,255,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
], dtype=float)

blue_filter =np.array([
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
])

edge_filter_horizontal = np.array([
    [-1, -2, -1],
    [0, 0, 0,],
    [1, 2, 1]
])

edge_filter_vertical = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

blurred = convolve(image, blue_filter)
h_edge = convolve(image, edge_filter_horizontal)
v_edge = convolve(image, edge_filter_vertical)

fig, axes = plt.subplots(1, 4, figsize=(16, 4))
axes[0].imshow(image, cmap='gray');axes[0].set_title("Original")
axes[1].imshow(blurred, cmap='gray');axes[1].set_title("Blurred")
axes[2].imshow(h_edge, cmap='gray');axes[2].set_title("Horizontal Edges")
axes[3].imshow(v_edge, cmap='gray');axes[3].set_title("Vertical Edges")
for ax in axes:
  ax.axis('off')
plt.tight_layout()
plt.show()
print("KEY INSIGHT: A CNN LEARNS these filters automatically from data!")

def max_pool2d (image,pool_size=2):
  h, w= image.shape
  out_h, out_w = h//pool_size, w//pool_size
  output = np.zeros((out_h, out_w))
  for i in range(out_h):
    for j in range(out_w):
      region = image[i*pool_size:(i+1)*pool_size, j*pool_size:(j+1)*pool_size]
      output[i,j] = np.max(region)
  return output

  pooled = max_pool2d(image, pool_size=2)
  print(f"Original shape: {image.shape}, Pooled shape: {pooled.shape}")

"""**DAY SEVEN**


**DAY EIGHT**


**DAY NINE**
"""

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_dataset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = torchvision.datasets.MNIST(root='./data', train=False, download=True, transform=transform)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=1000, shuffle=False)
print(f"Train set size: {len(train_dataset)}")
print(f"Test set size: {len(test_dataset)}")

class MnistCNN(nn.Module):
  def __init__(self):
    super().__init__()

    self.conv1=nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3)
    self.pool=nn.MaxPool2d(kernel_size=2, stride=2)

    self.conv2=nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3)

    self.fc1 = nn.Linear(64*5*5,128)
    self.fc2 = nn.Linear(128,10)

  def forward(self, x):
    x = self.pool(torch.relu(self.conv1(x)))
    x = self.pool(torch.relu(self.conv2(x)))
    x = x.view(-1, 64*5*5)
    x = torch.relu(self.fc1(x))
    x = self.fc2(x)
    return x

    self.dropout =nn.Dropout(0.5)
    self.bn1=nn.BatchNorm2d(32)
    self.bn2=nn.BatchNorm2d(64)

    x = self.pool(torch.relu(self.bn1(self.conv1(x))))
    x = self.pool(torch.relu(self.bn2(self.conv2(x))))
    x = x.view(-1, 64*5*5)
    x = self.dropout(x)
    x = torch.relu(torch.relu(self.fc1(x)))
    x = self.fc2(x)


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = MnistCNN().to(device)
print(model)
print("total parameters:", sum(p.numel() for p in model.parameters()))

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# Train the model
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

for epoch in range(5):
  model.train()
  total_loss=0
  for batch_x, batch_y in train_loader:
    batch_x, batch_y = batch_x.to(device), batch_y.to(device)
    pred = model(batch_x)
    loss = criterion(pred, batch_y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    total_loss += loss.item()
  print(f"Epoch {epoch+1}/5- Loss: {total_loss/len(train_loader):.4f}")

  model.eval()
  correct, total=0,0
  with torch.no_grad():
    for batch_x, batch_y in test_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        outputs = model(batch_x)
        predicted = outputs.argmax(dim=1)
        total += batch_y.size(0)
        correct += (predicted == batch_y).sum().item()

        print(f"Accuracy: {100*correct/total:.2f}%")

transform = transforms.Compose([
    transforms.Resize((128,128)),
    transforms.ToTensor()
])